### ISSUE TITLE
Critical NPE when editing values

### ISSUE THREAD

**Issue by morungos** [pughlab/tracker#106]
We've seen an error show when editing a value, and it's embedded in the scripting system, so it isn't really issue if you remove all the scripts, but where's the fun in that. Here's the backtrace:

```
Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
	...
	at ca.uhnresearch.pughlab.tracker.filter.TransactionFilter$1.doInTransactionWithoutResult(TransactionFilter.java:48)
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at ca.uhnresearch.pughlab.tracker.filter.TransactionFilter.tryFilter(TransactionFilter.java:59)
	at ca.uhnresearch.pughlab.tracker.filter.TransactionFilter.doFilter(TransactionFilter.java:74)
	...
	at java.lang.Thread.run(Thread.java:745)
Caused by: <eval>:14 TypeError: null has no such function "asText"
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.linkNull(NashornBottomLinker.java:172)
	at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.getGuardedInvocation(NashornBottomLinker.java:64)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:149)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:233)
	at jdk.nashorn.internal.scripts.Script$Recompilation$1$414A$\^eval\_.L:10(<eval>:14)
	at ca.uhnresearch.pughlab.tracker.scripting.JSEventHandler$$NashornJavaAdapter.run(Unknown Source)
	at ca.uhnresearch.pughlab.tracker.scripting.ScriptEventHandler.sendMessage(ScriptEventHandler.java:30)
	at ca.uhnresearch.pughlab.tracker.events.MultipleEventDispatcher.sendMessage(MultipleEventDispatcher.java:16)
	at ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl.setQueryAttributes(StudyRepositoryImpl.java:577)
	at ca.uhnresearch.pughlab.tracker.resource.EntityFieldResource.putResource(EntityFieldResource.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:521)
	... 124 more
```

**Comment by morungos** [comment]
The corresponding JS is below. Note that `as_text()` is only called on a few things, and the field is definitely suspicious as we did change this. 

It would be good to test this.

```
events.get("DEMO").on("field", function(event) { 
    var parameters = event.data.parameters;
    console.log("Parameters", parameters);
    var study = parameters.get("study").asText();
    var view = parameters.get("view").asText();
    var field = parameters.get("field").asText();
    var newValue = parameters.get("new").getValue();
    if (field == "returnRequested") {
        study = repository.getStudy(study);
        view = repository.getStudyView(study, view);
        var c = repository.getStudyCase(study, view, parameters.get("case_id").asInt());
        var oldState = c.getState();
        var newState = (newValue.toString() == "true") ? "returnPending" : null;
        if (oldState != newState) {
            repository.setStudyCaseState(study, view, c, event.data.user, newState);
        }
    }
});
```

**Comment by morungos** [comment]
Removed critical marker, as tis is only active for the DEMO study, not for anything else

**Comment by morungos** [comment]
Well, no. It's more subtle than I thought. We added a whole query system for the case selection, and when we did, we dropped the exposed view in the event system. So now we don't inform the JS which view is being used. Although it's far from clear that the view should be exposed to the JS, and most of the time it's more than a bit pointless.
