### ISSUE TITLE
Logging start error on Debian

### ISSUE THREAD

**Issue by morungos** [pughlab/tracker#117]
It's probably a permissions issue, but we're getting a logging error when starting up:

```
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.AccessDeniedException: server.0.0.log.lck
java.nio.file.AccessDeniedException: server.0.0.log.lck
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at java.util.logging.FileHandler.openFiles(FileHandler.java:459)
	at java.util.logging.FileHandler.<init>(FileHandler.java:263)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.logging.LogManager$5.run(LogManager.java:966)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
	at java.util.logging.LogManager.addLogger(LogManager.java:1165)
	at java.util.logging.LogManager.demandLogger(LogManager.java:556)
	at java.util.logging.Logger.demandLogger(Logger.java:455)
	at java.util.logging.Logger.getLogger(Logger.java:502)
	at org.restlet.engine.log.LoggerFacade.getLogger(LoggerFacade.java:117)
```

**Comment by morungos** [comment]
This is actually a problem for https://github.com/pughlab/java-server, because that's where this is set up. Let's also worry about the embedding of the filename in the jar. Running from a different working directory might help, but really this is better in a Jetty config.
