### ISSUE TITLE
Filters with run-time issues cause error redirects

### ISSUE THREAD

**Issue by morungos** [pughlab/tracker#125]
When there's an error in a filter query, we get redirected to a new page rather than generating some kind of an alert, which would be very preferable. 

For example: 

```
Caused by: org.springframework.dao.DataIntegrityViolationException: SQLQuery; SQL [from cases cases
where cases.ID in (select cases.ID
from cases cases
inner join attributes flt0
on flt0.ID = ? and flt0.STUDY_ID = cases.STUDY_ID
left join case_attribute_dates flv0
on flv0.ATTRIBUTE_ID = flt0.ID and flv0.CASE_ID = cases.ID
inner join attributes flt1
on flt1.ID = ? and flt1.STUDY_ID = cases.STUDY_ID
left join case_attribute_strings flv1
on flv1.ATTRIBUTE_ID = flt1.ID and flv1.CASE_ID = cases.ID
where cases.STUDY_ID = ? and flv0."VALUE" = ? and flv1."VALUE" = ?)]; data exception: invalid datetime format; nested exception is java.sql.SQLDataExc
eption: data exception: invalid datetime format
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:82)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate.translateQueryException(QueryDslJdbcTemplate.java:326)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate.access$000(QueryDslJdbcTemplate.java:74)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate$7.doInConnection(QueryDslJdbcTemplate.java:251)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate$7.doInConnection(QueryDslJdbcTemplate.java:244)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:350)
```

Generates an error redirect which isn't wonderfully readable.

**Comment by morungos** [comment]
There's a bunch more to this problem, but we aren't going to get to them today. First a start, the interceptors are supposed to reject error responses, and they don't. They are generating events, though, and this isn't really right either. Also, we should handle the deprecation of success callbacks.
