### ISSUE TITLE
SQL error on role permissions

### ISSUE THREAD

**Issue by morungos** [pughlab/tracker#14]
Stack backtrace is:

```
Caused by: java.sql.SQLException: Field 'role_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1990)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2151)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2625)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2119)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2415)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2333)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2318)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at com.mysema.query.sql.dml.SQLInsertClause.execute(SQLInsertClause.java:380)
	at ca.uhnresearch.pughlab.tracker.dao.impl.AuthorizationRepositoryImpl$9.doInSqlInsertClause(AuthorizationRepositoryImpl.java:184)
```

**Comment by morungos** [comment]
This seems to be fixed in 9404e9267, by re-reading the role after saving. Then we should be certain to have an identifier for a role that exists in the DB
