### ISSUE TITLE
Can't create a new attribute for an empty study from the UI

### ISSUE THREAD

**Issue by morungos** [pughlab/tracker#152]
Error message: 

    Cannot read property 'push' of undefined
    at Scope.$scope.newAttribute (http://clintracker.uhnresearch.ca/statics/app/js/admin/admin-study-attribute-editor-controller.js:37:30)
    at fn (eval at <anonymous> (http://clintracker.uhnresearch.ca/statics/vendors/js/angular/angular.js:13365:15), <anonymous>:4:227)
    at callback (http://clintracker.uhnresearch.ca/statics/vendors/js/angular/angular.js:23613:17)
    at Scope.$eval (http://clintracker.uhnresearch.ca/statics/vendors/js/angular/angular.js:16052:28)
    at Scope.$apply (http://clintracker.uhnresearch.ca/statics/vendors/js/angular/angular.js:16152:25)
    at HTMLButtonElement.<anonymous> (http://clintracker.uhnresearch.ca/statics/vendors/js/angular/angular.js:23618:23)
    at HTMLButtonElement.jQuery.event.dispatch (http://clintracker.uhnresearch.ca/statics/vendors/js/jquery/dist/jquery.js:4670:9)
    at HTMLButtonElement.elemData.handle (http://clintracker.uhnresearch.ca/statics/vendors/js/jque

**Comment by morungos** [comment]
Resolved in e04a954
