### ISSUE TITLE
Delete is broken on MySQL

### ISSUE THREAD

**Issue by morungos** [pughlab/tracker#159]
It's a dialect limitation: we get:

    Caused by: java.sql.SQLException: You can't specify target table 'CASES' for update in FROM clause
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1990)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2151)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2625)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2119)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2415)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2333)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2318)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at com.mysema.query.sql.dml.SQLDeleteClause.execute(SQLDeleteClause.java:193)
	at ca.uhnresearch.pughlab.tracker.dao.impl.CaseAttributePersistence$5.doInSqlDeleteClause(CaseAttributePersistence.java:583)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate$11.doInConnection(QueryDslJdbcTemplate.java:305)

We need to get the identifiers and then delete them, I guess.

**Comment by morungos** [comment]
Can't reproduce, but I did fix this
