### ISSUE TITLE
Weird HSQLDB error 

### ISSUE THREAD

**Issue by morungos** [pughlab/tracker#19]
Getting, suddenly, a very strange HSQLDB error, which I've not seen before. The actual source of the error is not very clear, and it probably isn't an issue with a production environment (which is unlikely to use HSQLDB). 

```
Caused by: org.hsqldb.HsqlException: invalid authorization specification
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.rights.User.checkPassword(Unknown Source)
	at org.hsqldb.rights.UserManager.getUser(Unknown Source)
	at org.hsqldb.Database.connect(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
```

**Comment by morungos** [comment]
Interestingly, this is not happening on the CI server.
