### ISSUE TITLE
Error editing spreadsheets in Java version of Tracker

### ISSUE THREAD

**Issue by morungos** [pughlab/tracker#22]
When editing in Tracker spreadsheet (LTS project) in the BCL-XL field, the following message appears:

Sorry! Unexpected error from service handling PUT /api/studies/LTS/views/LTS.clinical/entities/18101/bcl_xl: undefined

Similar message appears when trying to edit other fields.

**Comment by morungos** [comment]
Seems to be a DB issue:

```
Caused by: org.springframework.dao.DataIntegrityViolationException: SQLInsertClause; SQL [insert into case_attribute_strings (CASE_ID, ATTRIBUTE, VALUE, NOT_AVAILABLE)
values (?, ?, ?, ?)]; Field 'modified' doesn't have a default value; nested exception is java.sql.SQLException: Field 'modified' doesn't have a default value
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:243)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate.translateQueryException(QueryDslJdbcTemplate.java:326)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate.access$000(QueryDslJdbcTemplate.java:74)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate$8.doInConnection(QueryDslJdbcTemplate.java:265)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate$8.doInConnection(QueryDslJdbcTemplate.java:258)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:350)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate.insert(QueryDslJdbcTemplate.java:258)
	at ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl.writeCaseAttributeValue(StudyRepositoryImpl.java:745)
	at ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl.setCaseAttributeValue(StudyRepositoryImpl.java:664)
	at ca.uhnresearch.pughlab.tracker.resource.EntityFieldResource.putResource(EntityFieldResource.java:60)
```
