### ISSUE TITLE
Channel closed error shows in the logs

### ISSUE THREAD

**Issue by morungos** [pughlab/tracker#36]
Complete backtrace is (unhelpfully):

```
WARNING [org.apache.mina.util.DefaultExceptionMonitor] Unexpected exception.
java.nio.channels.ClosedSelectorException
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:84)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at org.apache.mina.transport.socket.nio.NioProcessor.select(NioProcessor.java:97)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1074)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

I'm guessing it's to do with LDAP connections being closed, but I can't be sure yet.

**Comment by morungos** [comment]
Oh noes, another one which is different:

```
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:487)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170)
	... 56 more
```

**Comment by morungos** [comment]
It's very possible that one or both of these actually relates to the logout crashing and analyics logic in #62 and #99. We need to watch for them, but it's possible we won't see them again.

**Comment by morungos** [comment]
Neither of these have been reported in either log for two months now, so closing seems appropriate.
