### ISSUE TITLE
Date format error causing views to fail

### ISSUE THREAD

**Issue by morungos** [pughlab/tracker#45]
Reported by Vanessa:

```
Caused by: org.springframework.dao.TransientDataAccessResourceException: SQLQuery; SQL [from (select cases.ID
from cases cases
where cases.STUDY_ID = ?) as cases
inner join case_attribute_dates case_attribute_dates
on cases.ID = case_attribute_dates.CASE_ID]; Value '0000-00-00' can not be represented as java.sql.Date; nested exception is java.sql.SQLException: Value '0000-00-00' can not be represented as java.sql.Date
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:108)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate.translateQueryException(QueryDslJdbcTemplate.java:326)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate.access$000(QueryDslJdbcTemplate.java:74)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate$7.doInConnection(QueryDslJdbcTemplate.java:251)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate$7.doInConnection(QueryDslJdbcTemplate.java:244)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:350)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate.query(QueryDslJdbcTemplate.java:244)
	at ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl.getJsonData(StudyRepositoryImpl.java:479)
	at ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl.getData(StudyRepositoryImpl.java:511)
	at ca.uhnresearch.pughlab.tracker.resource.ViewDataResource.buildResponseDTO(ViewDataResource.java:60)
	at ca.uhnresearch.pughlab.tracker.resource.ViewDataResource.getResource(ViewDataResource.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:524)
	... 107 more
```

**Comment by morungos** [comment]
I think this is bad data from import, maybe, but we shouldn't suddenly be getting this problem. See: http://stackoverflow.com/a/17196386/2140998

Temporary fix:

```
update case_attribute_dates set value = null, not_available = 1 where value = '0000-00-00';
```

But we need to stop this value being written in, both from import and editing

**Comment by morungos** [comment]
Yes, this is what happens when an empty string is written into the `case_attribute_dates` table in MySQL. These should be patched to null. We're getting these from fields that use a matcher to split dates and times.
