### ISSUE TITLE
Unable to add new rows.

### ISSUE THREAD

**Issue by jeffpbruce** [pughlab/tracker#76]
When I try to add content to the last (empty) row of the GENIUS tracker, I receive this error: "Sorry! Unexpected error from service handling POST /api/studies/GENIUS/views/primary/entities: undefined."

Similarly, when I try to add new content to an existing row, I receive this error: "Sorry! Unexpected error from service handling PUT /api/studies/GENIUS/views/primary/entities/24848/TransferNotes: undefined"

**Comment by morungos** [comment]
Early indications imply this is a websocket issue. At the very least, exceptions in websockets shouldn't entirely kill functionality. This means we really need some kind of a hot fix on this.

Stack trace:

```
FINE    [ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl] Got a study: ca.uhnresearch.pughlab.tracker.dto.Study@4fdd816f
FINE    [ca.uhnresearch.pughlab.tracker.extractor.StudyExtractor] Authenticated as: jbruce@ads.uhnresearch.ca
FINE    [ca.uhnresearch.pughlab.tracker.extractor.StudyExtractor] Checking permission for: GENIUS:view
FINE    [ca.uhnresearch.pughlab.tracker.extractor.StudyExtractor] OK, continuing with the study: GENIUS
FINE    [ca.uhnresearch.pughlab.tracker.extractor.ViewExtractor] Called ViewExtractor beforeHandle: primary
FINE    [ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl] Looking for study by name: primary
FINE    [ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl] Got a view: ca.uhnresearch.pughlab.tracker.dto.View@77ac3a67
FINE    [ca.uhnresearch.pughlab.tracker.extractor.ViewExtractor] OK, continuing with the view: primary
FINE    [ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl] Looking for case by identifier: 24848
FINE    [ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl] Got a case: ca.uhnresearch.pughlab.tracker.dto.Cases@6ad35e69
FINE    [ca.uhnresearch.pughlab.tracker.extractor.EntityExtractor] Continuing with the entity: ca.uhnresearch.pughlab.tracker.dto.Cases@6ad35e69
FINE    [ca.uhnresearch.pughlab.tracker.resource.EntityFieldResource] Called putResource() in EntityFieldResource
FINE    [ca.uhnresearch.pughlab.tracker.sockets.SocketEventService] Sending message to everyone watching: GENIUS
SEVERE  [ca.uhnresearch.pughlab.tracker.sockets.SocketEventService] Whoa! Something removed a resource: c2dc88a5-4119-4821-98fe-80b2649ffe95, null
WARNING [org.restlet] Exception or error caught in server resource
Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:540)
	at org.restlet.resource.ServerResource.put(ServerResource.java:1435)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:610)
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:679)
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:357)
	at org.restlet.resource.ServerResource.handle(ServerResource.java:1044)
	at org.restlet.resource.Finder.handle(Finder.java:236)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75)
	at org.restlet.Application.handle(Application.java:385)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.Component.handle(Component.java:408)
	at org.restlet.Server.handle(Server.java:507)
	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at ca.uhnresearch.pughlab.tracker.filter.TransactionFilter$1.doInTransactionWithoutResult(TransactionFilter.java:47)
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at ca.uhnresearch.pughlab.tracker.filter.TransactionFilter.doFilter(TransactionFilter.java:57)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Whoa! Something removed a resource: c2dc88a5-4119-4821-98fe-80b2649ffe95
	at ca.uhnresearch.pughlab.tracker.sockets.SocketEventService.checkResource(SocketEventService.java:58)
	at ca.uhnresearch.pughlab.tracker.sockets.SocketEventService.sendMessage(SocketEventService.java:80)
	at ca.uhnresearch.pughlab.tracker.events.impl.SocketUpdateEventService.sendMessage(SocketUpdateEventService.java:13)
	at ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl.sendUpdateEvent(StudyRepositoryImpl.java:640)
	at ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl.setCaseAttributeValue(StudyRepositoryImpl.java:622)
	at ca.uhnresearch.pughlab.tracker.resource.EntityFieldResource.putResource(EntityFieldResource.java:65)
	at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:521)
	... 117 more
```

**Comment by morungos** [comment]
@jeffpbruce Can you maybe tell me what browser you were using? I can prevent this issue from being so bad fairly easily, but I'm very curious what the underlying cause is.

**Comment by jeffpbruce** [comment]
I tried them all! Chrome, safari, and Firefox. Seemed to get the get the
same error each time - although when I switched to Firefox it worked for a
time before throwing the error again.

**Comment by morungos** [comment]
Yes, this isn't enough. Now we get some weird additional event notifications going on.

**Comment by jeffpbruce** [comment]
This issue appears to have new life... I'm getting this message again when I attempt to edit cells:
Sorry! Unexpected error from service handling PUT /api/studies/GENIUS/views/primary/entities/11572/SequencingStatus: undefined

**Comment by morungos** [comment]
It's similar effect, but seems to be a different cause, a transaction deadlock (!). I'll close and open a new ticket
