### ISSUE TITLE
Transaction deadlock when writing data

### ISSUE THREAD

**Issue by morungos** [pughlab/tracker#89]
Stack trace:

```
INFO    [ca.uhnresearch.pughlab.tracker.scripting.ScriptEventHandler] Got an event: ca.uhnresearch.pughlab.tracker.events.Event@2f9f53f1, GENIUS
FINE    [ca.uhnresearch.pughlab.tracker.extractor.AttributeExtractor] OK, continuing with the attribute: dateRegistration
FINE    [ca.uhnresearch.pughlab.tracker.scripting.ScriptEventHandler] Found handlers: field, []
FINE    [ca.uhnresearch.pughlab.tracker.resource.EntityFieldResource] Called putResource() in EntityFieldResource
FINE    [ca.uhnresearch.pughlab.tracker.sockets.SocketEventHandler] Sending message to everyone watching: GENIUS
FINE    [ca.uhnresearch.pughlab.tracker.sockets.SocketEventHandler] Checking: af6729bc-55cb-4293-94ad-d9df5803c20e, AtmosphereResource{
	 uuid=af6729bc-55cb-4293-94ad-d9df5803c20e,
	 transport=WEBSOCKET,
	 isInScope=true,
	 isResumed=false,
	 isCancelled=false,
	 isSuspended=true,
	 broadcasters=/events,
	 isClosedByClient=false,
	 isClosedByApplication=false,
	 action=Action{timeout=-1, type=SUSPEND}}
FINE    [ca.uhnresearch.pughlab.tracker.sockets.SocketEventHandler] Sending to: af6729bc-55cb-4293-94ad-d9df5803c20e, {"type":"field","data":{"user":"jbruce@ads.uhnresearch.ca","scope":"GENIUS","time":1444245742586,"parameters":{"field":"DiseaseSite","case_id":24858,"study_id":3,"study":"GENIUS","view":"primary","old":"REDACTED","new":"REDACTED"}}}
FINE    [ca.uhnresearch.pughlab.tracker.sockets.SocketEventHandler] Checking: 611b300a-2eb7-4c72-9f89-38cf79ed44f8, AtmosphereResource{
	 uuid=611b300a-2eb7-4c72-9f89-38cf79ed44f8,
	 transport=WEBSOCKET,
	 isInScope=true,
	 isResumed=false,
	 isCancelled=false,
	 isSuspended=true,
	 broadcasters=/events,
	 isClosedByClient=false,
	 isClosedByApplication=false,
	 action=Action{timeout=-1, type=SUSPEND}}
FINE    [ca.uhnresearch.pughlab.tracker.sockets.SocketEventHandler] Sending to: 611b300a-2eb7-4c72-9f89-38cf79ed44f8, {"type":"field","data":{"user":"jbruce@ads.uhnresearch.ca","scope":"GENIUS","time":1444245742586,"parameters":{"field":"DiseaseSite","case_id":24858,"study_id":3,"study":"GENIUS","view":"primary","old":"REDACTED","new":"REDACTED"}}}
INFO    [http] 2015-10-07	15:22:22	205.210.128.135	jbruce@ads.uhnresearch.ca	127.0.0.1	80	PUT	/api/studies/GENIUS/views/primary/entities/24858/DiseaseSite	-	200	-	14	37	http://clintracker.uhnresearch.ca	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36	http://clintracker.uhnresearch.ca/studies/GENIUS/view/primary
FINE    [ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl] Looking for study by name: GENIUS
FINE    [ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl] Got a study: ca.uhnresearch.pughlab.tracker.dto.Study@7a867029
FINE    [ca.uhnresearch.pughlab.tracker.extractor.StudyExtractor] Authenticated as: jbruce@ads.uhnresearch.ca
FINE    [ca.uhnresearch.pughlab.tracker.extractor.StudyExtractor] Checking permission for: GENIUS:view
FINE    [ca.uhnresearch.pughlab.tracker.extractor.StudyExtractor] OK, continuing with the study: GENIUS
FINE    [ca.uhnresearch.pughlab.tracker.extractor.ViewExtractor] Called ViewExtractor beforeHandle: primary
FINE    [ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl] Looking for study by name: primary
FINE    [ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl] Got a view: ca.uhnresearch.pughlab.tracker.dto.View@2e3bc473
FINE    [ca.uhnresearch.pughlab.tracker.extractor.ViewExtractor] OK, continuing with the view: primary
FINE    [ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl] Looking for case by identifier: 24858
FINE    [ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl] Got a case: ca.uhnresearch.pughlab.tracker.dto.Cases@13834d35
FINE    [ca.uhnresearch.pughlab.tracker.extractor.EntityExtractor] Continuing with the entity: ca.uhnresearch.pughlab.tracker.dto.Cases@13834d35
FINE    [ca.uhnresearch.pughlab.tracker.extractor.AttributeExtractor] Called AttributeExtractor beforeHandle: GENIUSID
FINE    [ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl] Looking for study attribute: GENIUSID
FINE    [ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl] Executing query: from attributes attributes
where attributes.STUDY_ID = ? and attributes.NAME = ?
FINE    [ca.uhnresearch.pughlab.tracker.extractor.AttributeExtractor] OK, continuing with the attribute: GENIUSID
FINE    [ca.uhnresearch.pughlab.tracker.resource.EntityFieldResource] Called putResource() in EntityFieldResource
INFO    [ca.uhnresearch.pughlab.tracker.scripting.ScriptEventHandler] Got an event: ca.uhnresearch.pughlab.tracker.events.Event@548f9cfb, GENIUS
FINE    [ca.uhnresearch.pughlab.tracker.scripting.ScriptEventHandler] Found handlers: field, []
INFO    [org.springframework.jdbc.support.SQLErrorCodesFactory] SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana]
WARNING [org.restlet] Exception or error caught in server resource
Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:540)
	at org.restlet.resource.ServerResource.put(ServerResource.java:1435)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:610)
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:679)
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:357)
	at org.restlet.resource.ServerResource.handle(ServerResource.java:1044)
	at org.restlet.resource.Finder.handle(Finder.java:236)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75)
	at org.restlet.Application.handle(Application.java:385)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.Component.handle(Component.java:408)
	at org.restlet.Server.handle(Server.java:507)
	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at ca.uhnresearch.pughlab.tracker.filter.TransactionFilter$1.doInTransactionWithoutResult(TransactionFilter.java:47)
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at ca.uhnresearch.pughlab.tracker.filter.TransactionFilter.doFilter(TransactionFilter.java:57)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.dao.DeadlockLoserDataAccessException: SQLInsertClause; SQL [insert into case_attribute_strings (CASE_ID, ATTRIBUTE_ID, VALUE, NOT_AVAILABLE)
values (?, ?, ?, ?)]; Deadlock found when trying to get lock; try restarting transaction; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:263)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate.translateQueryException(QueryDslJdbcTemplate.java:326)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate.access$000(QueryDslJdbcTemplate.java:74)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate$8.doInConnection(QueryDslJdbcTemplate.java:265)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate$8.doInConnection(QueryDslJdbcTemplate.java:258)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:350)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate.insert(QueryDslJdbcTemplate.java:258)
	at ca.uhnresearch.pughlab.tracker.dao.impl.CaseAttributePersistence.writeCaseAttributeValue(CaseAttributePersistence.java:145)
	at ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl.setCaseAttributeValue(StudyRepositoryImpl.java:691)
	at ca.uhnresearch.pughlab.tracker.resource.EntityFieldResource.putResource(EntityFieldResource.java:70)
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:521)
	... 119 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1064)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1990)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2151)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2625)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2119)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2415)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2333)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2318)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at com.mysema.query.sql.dml.SQLInsertClause.execute(SQLInsertClause.java:380)
	at ca.uhnresearch.pughlab.tracker.dao.impl.CaseAttributePersistence$2.doInSqlInsertClause(CaseAttributePersistence.java:149)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate$8.doInConnection(QueryDslJdbcTemplate.java:263)
	... 129 more
```

**Comment by morungos** [comment]
And now we're getting inconsistencies....

```
Caused by: org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 2
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate.queryForObject(QueryDslJdbcTemplate.java:220)
	at ca.uhnresearch.pughlab.tracker.dao.impl.CaseAttributePersistence.getOldCaseAttributeValue(CaseAttributePersistence.java:174)
	at ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl.setCaseAttributeValue(StudyRepositoryImpl.java:689)
	at ca.uhnresearch.pughlab.tracker.resource.EntityFieldResource.putResource(EntityFieldResource.java:70)
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:521)
	... 119 more
```
