### ISSUE TITLE
Serialization failures when pasting multiple cells

### ISSUE THREAD

**Issue by morungos** [pughlab/tracker#96]
Although not, seemingly, when pasting each individually. And it looks like it's mixing types of cells that's the issue. Stack backtrace:

```
where view_attributes.VIEW_ID = ?]; transaction rollback: serialization failure; nested exception is java.sql.SQLTransactionRollbackException: transac
tion rollback: serialization failure
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:71)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate.translateQueryException(QueryDslJdbcTemplate.java:326)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate.access$000(QueryDslJdbcTemplate.java:74)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate$7.doInConnection(QueryDslJdbcTemplate.java:251)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate$7.doInConnection(QueryDslJdbcTemplate.java:244)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:350)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate.query(QueryDslJdbcTemplate.java:244)
	at ca.uhnresearch.pughlab.tracker.dao.impl.CaseAttributePersistence.addCaseTuples(CaseAttributePersistence.java:90)
	at ca.uhnresearch.pughlab.tracker.dao.impl.CaseAttributePersistence.getJsonData(CaseAttributePersistence.java:108)
	at ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl.getCaseData(StudyRepositoryImpl.java:569)
	at ca.uhnresearch.pughlab.tracker.dao.impl.StudyRepositoryImpl.getCaseAttributeValue(StudyRepositoryImpl.java:649)
	at ca.uhnresearch.pughlab.tracker.resource.EntityFieldResource.buildResponseDTO(EntityFieldResource.java:108)
	at ca.uhnresearch.pughlab.tracker.resource.EntityFieldResource.getResource(EntityFieldResource.java:86)
	at ca.uhnresearch.pughlab.tracker.resource.EntityFieldResource.putResource(EntityFieldResource.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:521)
	... 125 more
Caused by: java.sql.SQLTransactionRollbackException: transaction rollback: serialization failure
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeQuery(Unknown Source)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at com.mysema.query.sql.AbstractSQLQuery.list(AbstractSQLQuery.java:315)
	at org.springframework.data.jdbc.query.QueryDslJdbcTemplate$7.doInConnection(QueryDslJdbcTemplate.java:249)
	... 140 more
Caused by: org.hsqldb.HsqlException: transaction rollback: serialization failure
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 146 more


```

**Comment by morungos** [comment]
This required switching to MVCC for transaction handling. Resolved in a495a5f
