### ISSUE TITLE
NullPointerException when logging out

### ISSUE THREAD

**Issue by morungos** [pughlab/tracker#99]
It's possibly a minor problem, but we've observed this in the logs.

```
2015-10-29 12:28:37.823:WARN:oejs.ServletHandler:/api/authentication/logout
java.lang.NullPointerException
	at ca.uhnresearch.pughlab.tracker.security.AuditedSecurityManager.logout(AuditedSecurityManager.java:32)
	at org.apache.shiro.subject.support.DelegatingSubject.logout(DelegatingSubject.java:363)
	at org.apache.shiro.web.filter.authc.LogoutFilter.preHandle(LogoutFilter.java:71)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:131)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
```

**Comment by morungos** [comment]
Hardly a surprise when reading the code. The username is accessed after the logout has been processed.
